from enum import Enum


class ResponseCode(str, Enum):
    SUCCESS = "SUCCESS"
    INVALID_REQUEST = "INVALID_REQUEST"
    ODOO_AUTHENTICATION_ERROR = "ODOO_AUTHENTICATION_ERROR"
    ODOO_CONNECTION_ERROR = "ODOO_CONNECTION_ERROR"
    ODOO_BUSINESS_ERROR = "ODOO_BUSINESS_ERROR"
    INTERNAL_ERROR = "INTERNAL_ERROR"
