from app.routing.taxonomy import Intent
from app.tools.definitions import (
    Domain,
    HttpMethod,
    LeaveActionableArguments,
    LeaveBalanceArguments,
    LeaveCancelArguments,
    LeaveCommandArguments,
    LeaveHistoryArguments,
    LeavePeriodArguments,
    LeaveRequestDetailsArguments,
    LeaveRequestStatusArguments,
    LeaveUpdateArguments,
    NoArguments,
    Operation,
    RiskLevel,
    RouteType,
    ToolDefinition,
)

_BASE = "/api/hrm-chatbot/v1/leave"


LEAVE_TOOLS = (
    ToolDefinition(
        name="leave_list_actionable_requests",
        domain=Domain.LEAVE,
        capability="leave.history",
        operation=Operation.LIST,
        route_type=RouteType.QUERY,
        risk_level=RiskLevel.READ,
        description="Liệt kê các đơn nghỉ hiện có thể sửa hoặc hủy.",
        endpoint=f"{_BASE}/requests/actionable",
        http_method=HttpMethod.GET,
        argument_schema=LeaveActionableArguments,
        examples=(
            "Các đơn nghỉ nào của tôi có thể sửa?",
            "Liệt kê đơn có thể cập nhật.",
            "Các yêu cầu nghỉ nào có thể hủy?",
            "Tải danh sách đơn được phép thao tác.",
            "Cho xem đơn nghỉ còn sửa được.",
        ),
        negative_examples=(
            "Sửa đơn nghỉ của tôi.",
            "Tạo đơn nghỉ mới.",
            "Số dư phép của tôi.",
        ),
    ),
    ToolDefinition(
        name="leave_get_request_details",
        domain=Domain.LEAVE,
        capability="leave.request_status",
        operation=Operation.GET,
        route_type=RouteType.QUERY,
        risk_level=RiskLevel.READ,
        description="Tải snapshot và quyền thao tác của đơn nghỉ đã chọn.",
        endpoint=f"{_BASE}/requests/{{request_id}}",
        http_method=HttpMethod.GET,
        argument_schema=LeaveRequestDetailsArguments,
        path_arguments=("request_id",),
        examples=(
            "Xem chi tiết đơn nghỉ đã chọn.",
            "Tải snapshot đơn để sửa.",
            "Kiểm tra đơn này còn hủy được không.",
            "Đọc dữ liệu hiện tại của đơn nghỉ.",
            "Lấy chi tiết yêu cầu nghỉ đã chọn.",
        ),
        negative_examples=(
            "Liệt kê lịch sử nghỉ phép.",
            "Tạo đơn nghỉ mới.",
            "Xem số dư phép.",
        ),
    ),
    ToolDefinition(
        name="leave_get_balance",
        domain=Domain.LEAVE,
        capability="leave.balance",
        operation=Operation.GET,
        route_type=RouteType.QUERY,
        risk_level=RiskLevel.READ,
        description="Lấy số phép còn lại theo năm và loại nghỉ.",
        endpoint=f"{_BASE}/current/balance",
        http_method=HttpMethod.POST,
        argument_schema=LeaveBalanceArguments,
        examples=(
            "Năm nay tôi còn bao nhiêu ngày phép?",
            "Số dư phép năm 2026 của tôi.",
            "Tôi còn lại mấy ngày nghỉ phép thường niên?",
            "Kiểm tra phép còn lại theo loại nghỉ.",
            "Quỹ phép của tôi hiện còn bao nhiêu?",
        ),
        negative_examples=(
            "Năm nay tôi đã dùng bao nhiêu ngày phép?",
            "Cho xem lịch sử các lần nghỉ của tôi.",
            "Tạo giúp tôi đơn nghỉ ngày mai.",
        ),
    ),
    ToolDefinition(
        name="leave_get_used",
        domain=Domain.LEAVE,
        capability="leave.used",
        operation=Operation.GET,
        route_type=RouteType.QUERY,
        risk_level=RiskLevel.READ,
        description="Lấy số phép đã sử dụng theo năm và loại nghỉ.",
        endpoint=f"{_BASE}/current/used",
        http_method=HttpMethod.POST,
        argument_schema=LeaveBalanceArguments,
        examples=(
            "Năm nay tôi đã nghỉ phép bao nhiêu ngày?",
            "Số phép đã sử dụng trong năm 2026.",
            "Tôi đã dùng mấy ngày nghỉ thường niên?",
            "Thống kê lượng phép đã tiêu theo loại nghỉ.",
            "Quỹ phép của tôi đã dùng hết bao nhiêu?",
        ),
        negative_examples=(
            "Tôi còn bao nhiêu ngày phép chưa dùng?",
            "Liệt kê từng đơn nghỉ trước đây.",
            "Đơn nghỉ gần nhất được duyệt chưa?",
        ),
    ),
    ToolDefinition(
        name="leave_get_history",
        domain=Domain.LEAVE,
        capability="leave.history",
        intents=frozenset(
            {Intent.LEAVE_HISTORY, Intent.LEAVE_REQUEST_STATUS}
        ),
        operation=Operation.LIST,
        route_type=RouteType.QUERY,
        risk_level=RiskLevel.READ,
        description="Lấy lịch sử đơn nghỉ trong khoảng ngày và theo trạng thái.",
        endpoint=f"{_BASE}/current/history",
        http_method=HttpMethod.POST,
        argument_schema=LeaveHistoryArguments,
        examples=(
            "Cho xem lịch sử nghỉ phép từ đầu năm.",
            "Liệt kê các đơn nghỉ tôi đã gửi tháng trước.",
            "Các lần nghỉ đã được duyệt trong quý này.",
            "Tra cứu những đơn nghỉ bị từ chối.",
            "Tôi đã xin nghỉ những ngày nào gần đây?",
        ),
        negative_examples=(
            "Tôi còn bao nhiêu phép năm?",
            "Đơn nghỉ mã 123 đang ở trạng thái nào?",
            "Cho xem lịch nghỉ trên lịch tháng này.",
        ),
    ),
    ToolDefinition(
        name="leave_get_request_status",
        domain=Domain.LEAVE,
        capability="leave.request_status",
        operation=Operation.GET,
        route_type=RouteType.QUERY,
        risk_level=RiskLevel.READ,
        description="Lấy trạng thái hiện tại của một đơn nghỉ cụ thể.",
        endpoint=f"{_BASE}/current/request-status",
        http_method=HttpMethod.POST,
        argument_schema=LeaveRequestStatusArguments,
        examples=(
            "Đơn nghỉ mã 123 đã được duyệt chưa?",
            "Kiểm tra trạng thái yêu cầu nghỉ số 45.",
            "Đơn xin phép của tôi đang chờ ai xử lý?",
            "Yêu cầu nghỉ 88 có bị từ chối không?",
            "Tình trạng hiện tại của đơn nghỉ mã 19.",
            "Trạng thái đơn nghỉ phép của tôi.",
            "Đơn gần nhất thế nào?",
            "Đơn nghỉ gần nhất đã duyệt chưa?",
            "Đơn nghỉ đang ở trạng thái gì?",
            "don nghi da duyet chua",
        ),
        negative_examples=(
            "Liệt kê toàn bộ đơn nghỉ tháng này.",
            "Tôi còn bao nhiêu ngày phép?",
            "Hủy đơn nghỉ mã 123.",
        ),
    ),
    ToolDefinition(
        name="leave_get_calendar",
        domain=Domain.LEAVE,
        capability="leave.calendar",
        operation=Operation.GET,
        route_type=RouteType.QUERY,
        risk_level=RiskLevel.READ,
        description="Lấy dữ liệu nghỉ phép để hiển thị theo lịch.",
        endpoint=f"{_BASE}/current/calendar",
        http_method=HttpMethod.POST,
        argument_schema=LeaveHistoryArguments,
        examples=(
            "Hiển thị lịch nghỉ của tôi trong tháng này.",
            "Những ngày nào trên lịch tôi đã đăng ký nghỉ?",
            "Cho xem lịch phép từ ngày 1 đến ngày 31.",
            "Đánh dấu các ngày nghỉ đã duyệt trên lịch.",
            "Lịch nghỉ cá nhân trong quý tới.",
        ),
        negative_examples=(
            "Liệt kê chi tiết lịch sử đơn nghỉ.",
            "Đơn nghỉ mã 10 được duyệt chưa?",
            "Tạo đơn xin nghỉ cho thứ sáu.",
        ),
    ),
    ToolDefinition(
        name="leave_check_eligibility",
        domain=Domain.LEAVE,
        capability="leave.eligibility",
        operation=Operation.CHECK,
        route_type=RouteType.QUERY,
        risk_level=RiskLevel.READ,
        description="Kiểm tra điều kiện xin nghỉ trước khi tạo đơn.",
        endpoint=f"{_BASE}/current/eligibility",
        http_method=HttpMethod.POST,
        argument_schema=LeavePeriodArguments,
        examples=(
            "Tôi có đủ điều kiện nghỉ phép ngày mai không?",
            "Kiểm tra có thể xin nghỉ nửa ngày thứ hai không.",
            "Khoảng ngày này có hợp lệ để đăng ký nghỉ?",
            "Tôi có đủ số dư cho hai ngày nghỉ sắp tới không?",
            "Xác minh yêu cầu nghỉ theo giờ này có được phép không.",
        ),
        negative_examples=(
            "Tạo luôn đơn nghỉ cho ngày mai.",
            "Tôi còn bao nhiêu ngày phép?",
            "Đơn nghỉ đã gửi đang ở trạng thái gì?",
        ),
    ),
    ToolDefinition(
        name="leave_get_types",
        domain=Domain.LEAVE,
        capability="leave.types",
        operation=Operation.LIST,
        route_type=RouteType.QUERY,
        risk_level=RiskLevel.READ,
        description=(
            "Tra cứu danh sách các loại nghỉ mà người dùng được phép hoặc "
            "có thể đăng ký khi tạo đơn."
        ),
        endpoint=f"{_BASE}/types",
        http_method=HttpMethod.GET,
        argument_schema=NoArguments,
        examples=(
            "Có những loại nghỉ phép nào?",
            "Danh sách loại nghỉ tôi có thể đăng ký.",
            "Công ty đang áp dụng các nhóm phép gì?",
            "Cho xem mã và tên các loại nghỉ.",
            "Tôi được chọn những loại phép nào khi tạo đơn?",
            "Có những loại nghỉ nào tôi được đăng ký?",
        ),
        negative_examples=(
            "Số dư phép thường niên của tôi.",
            "Kiểm tra tôi có đủ điều kiện nghỉ ốm không.",
            "Tạo đơn nghỉ phép năm.",
        ),
    ),
    ToolDefinition(
        name="leave_create_request",
        domain=Domain.LEAVE,
        capability="leave.request.create",
        operation=Operation.CREATE,
        route_type=RouteType.COMMAND,
        risk_level=RiskLevel.WRITE,
        description="Tạo một đơn nghỉ mới sau khi người dùng xác nhận.",
        endpoint=f"{_BASE}/requests",
        http_method=HttpMethod.POST,
        argument_schema=LeaveCommandArguments,
        examples=(
            "Tạo đơn xin nghỉ ngày mai giúp tôi.",
            "Gửi yêu cầu nghỉ phép từ thứ hai đến thứ ba.",
            "Đăng ký cho tôi nghỉ nửa buổi chiều.",
            "Tôi xác nhận tạo đơn nghỉ theo giờ này.",
            "Lập đơn nghỉ phép năm với lý do việc gia đình.",
        ),
        negative_examples=(
            "Tôi có đủ điều kiện nghỉ ngày mai không?",
            "Đơn nghỉ mã 25 được duyệt chưa?",
            "Cập nhật lý do cho đơn nghỉ đã tạo.",
            "Số ngày phép còn lại.",
            "Lịch sử nghỉ phép.",
            "Trạng thái đơn nghỉ phép.",
            "Đơn nghỉ đã duyệt chưa.",
            "Số lần quên chấm công.",
            "Lịch sử chấm công.",
        ),
        requires_confirmation=True,
    ),
    ToolDefinition(
        name="leave_update_request",
        domain=Domain.LEAVE,
        capability="leave.request.update",
        operation=Operation.UPDATE,
        route_type=RouteType.COMMAND,
        risk_level=RiskLevel.WRITE,
        description="Cập nhật một đơn nghỉ hiện có sau khi xác nhận.",
        endpoint=f"{_BASE}/requests/{{request_id}}",
        http_method=HttpMethod.PATCH,
        argument_schema=LeaveUpdateArguments,
        path_arguments=("request_id",),
        examples=(
            "Sửa ngày kết thúc của đơn nghỉ gần nhất.",
            "Cập nhật lý do trong yêu cầu nghỉ đầu tiên.",
            "Đổi loại nghỉ của đơn ngày 10/8.",
            "Điều chỉnh thời gian của đơn thứ hai.",
            "Tôi muốn sửa nhiều thông tin của một đơn nghỉ.",
        ),
        negative_examples=(
            "Tạo một đơn nghỉ mới cho tuần sau.",
            "Hủy đơn nghỉ mã 25.",
            "Kiểm tra trạng thái đơn nghỉ số 18.",
        ),
        requires_confirmation=True,
    ),
    ToolDefinition(
        name="leave_cancel_request",
        domain=Domain.LEAVE,
        capability="leave.request.cancel",
        operation=Operation.CANCEL,
        route_type=RouteType.COMMAND,
        risk_level=RiskLevel.WRITE,
        description="Hủy một đơn nghỉ hiện có sau khi người dùng xác nhận.",
        endpoint=f"{_BASE}/requests/{{request_id}}/cancel",
        http_method=HttpMethod.POST,
        argument_schema=LeaveCancelArguments,
        path_arguments=("request_id",),
        examples=(
            "Hủy đơn nghỉ gần nhất giúp tôi.",
            "Tôi muốn rút yêu cầu nghỉ đầu tiên.",
            "Không nghỉ nữa, hãy hủy đơn ngày 10/8.",
            "Xóa bỏ yêu cầu nghỉ phép thứ hai.",
            "Thực hiện hủy một đơn xin nghỉ của tôi.",
        ),
        negative_examples=(
            "Cập nhật ngày nghỉ cho đơn mã 25.",
            "Đơn nghỉ số 18 đang ở trạng thái nào?",
            "Tạo đơn nghỉ thay thế cho tuần sau.",
        ),
        requires_confirmation=True,
    ),
)
